#!/usr/bin/bash
if [[ $# -eq 0 ]]; then
    ls
elif [[ $# -eq 1 && -d $1 ]]; then
    ls $1
elif [[ $# -eq 2 && -d $2 ]]; then
    if [[ $1 =~ -[ladiR] ]]; then
      ls $1 $2
    else
      echo "Error: Invalid option $1"
    fi
else
    echo "Error: Invalid arguments"
fi
#ls $@