#!/usr/bin/bash
if [[ $# == 2 ]]; then
    if [[ -f $1 ]]; then
        cat $1 > $2
    elif [[ -f $1 && -d $2 ]]; then
        cat $1 > $2/$1
    else
        echo "File not found"
    fi
elif [[ $# -gt 2 ]]; then
  dir="${@: -1}"
  if [[ -d $dir ]]; then
      cp $@
  else
      echo "Directory not found"
  fi
fi
